version: '3.8'

services:
  calculadora-envios:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: calculadora-envios-gls
    ports:
      - "46070:46070"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: npm run dev
