version: '3.8'

services:
  calculadora-envios:
    build: .
    container_name: calculadora-envios-gls
    ports:
      - "46070:46070"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
